# Product Management API - Docker Compose Configuration
# Developer: Phan Quốc Viễn (MSSV: 23110362)
# Chỉ chạy database và pgAdmin, ứng dụng chạy trực tiếp từ IntelliJ
version: '3.9'
services:
  db:
    image: postgres:16
    container_name: api_postgres
    environment:
      - POSTGRES_DB=api_db
      - POSTGRES_USER=api_user
      - POSTGRES_PASSWORD=api_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 3s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: api_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "8081:80"
    depends_on:
      - db
volumes:
  db_data:
